server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentcar
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      show-sql: true
      format-sql: true
